apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mongo
  name: mongo
  annotations:
    source: "https://github.com/saintdle/pacman-tanzu"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'pacman-app'
        vault.hashicorp.com/agent-inject-secret-mongodb-users-secret: 'secret/pacman'    
        vault.hashicorp.com/agent-inject-template-mongodb-users-secret: |
          {{ with secret "secret/pacman" -}}
            export MONGODB_ROOT_PASSWORD="{{ .Data.data.database_admin_password }}"
            export MONGODB_DATABASE="{{ .Data.data.database_name }}"
            export MONGODB_PASSWORD="{{ .Data.data.database_password }}"
            export MONGODB_USERNAME="{{ .Data.data.database_user }}"
          {{- end }}            
      labels:
        name: mongo
    spec:
      serviceAccountName: pacman-app
      initContainers:
      - args:
        - |
          mkdir -p /bitnami/mongodb
          chown -R "1001:1001" "/bitnami/mongodb"
        command:
        - /bin/bash
        - -ec
        image: docker.io/bitnami/bitnami-shell:10-debian-10-r158
        imagePullPolicy: Always
        name: volume-permissions
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bitnami/mongodb
          name: mongo-db
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      #serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mongo-db
        persistentVolumeClaim:
          claimName: mongo-storage
      containers:
      - image: bitnami/mongodb:4.4.8
        name: mongo
        args:
          - /bin/bash
          - -c
          - source /vault/secrets/mongodb-users-secret
        # - name: MONGODB_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       key: database-admin-password
        #       name: mongodb-users-secret
        # - name: MONGODB_DATABASE
        #   valueFrom:
        #     secretKeyRef:
        #       key: database-name
        #       name: mongodb-users-secret
        # - name: MONGODB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       key: database-password
        #       name: mongodb-users-secret
        # - name: MONGODB_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       key: database-user
        #       name: mongodb-users-secret
        readinessProbe:
          exec:
           command:
            - /bin/sh
            - -i
            - -c
            - source /vault/secrets/mongodb-users-secret
            - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USERNAME -p $MONGODB_PASSWORD
              --eval="quit()"
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
          - name: mongo-db
            mountPath: /bitnami/mongodb/