apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: pacman
  name: pacman
  annotations:
    source: "https://github.com/saintdle/pacman-tanzu"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pacman
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'pacman-app'
        vault.hashicorp.com/agent-inject-secret-mongodb-users-secret: 'secret/pacman'    
        vault.hashicorp.com/agent-inject-template-mongodb-users-secret: |
          {{ with secret "secret/pacman" -}}
            export MONGO_AUTH_PWD="{{ .Data.data.database_password }}"
            export MONGO_AUTH_USER="{{ .Data.data.database_user }}"
          {{- end }} 
      labels:
        name: pacman
    spec:
      serviceAccountName: pacman-app
      containers:
      - image: quay.io/ifont/pacman-nodejs-app:latest
        name: pacman
        ports:
        - containerPort: 8080
          name: http-server
          protocol: TCP
        command:
          - /bin/sh
          - -c
        args:
          - cat /vault/secrets/mongodb-users-secret && . /vault/secrets/mongodb-users-secret && env
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        env:
        - name: MONGO_SERVICE_HOST
          value: mongo
        # - name: MONGO_AUTH_USER
        #   valueFrom:
        #     secretKeyRef:
        #       key: database-user
        #       name: mongodb-users-secret
        # - name: MONGO_AUTH_PWD
        #   valueFrom:
        #     secretKeyRef:
        #       key: database-password
        #       name: mongodb-users-secret
        - name: MONGO_DATABASE
          value: pacman
        - name: MY_MONGO_PORT
          value: "27017"
        - name: MONGO_USE_SSL
          value: "false"
        - name: MONGO_VALIDATE_SSL
          value: "false"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
